apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: mova-erinnerungsbuch
data:
  API_ENDPOINT: https://mova-erinnerungsbuch.ch
  LOG_LEVEL: "40"
  NODE_PORT: "5173"
  REDIS_DATABASE: "3"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_TTL: "60"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mova-erinnerungsbuch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
      containers:
        - envFrom:
            - configMapRef:
                name: frontend
          image: ghcr.io/scout-ch/mova-erinnerungsbuch-frontend:latest@sha256:95d24cd6f8a57805b5664028447ed6e975005c35e840dd11c7550b55cf504c72
          name: frontend
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mova-erinnerungsbuch
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend
  namespace: mova-erinnerungsbuch
spec:
  parentRefs:
    - name: mova-erinnerungsbuch
      sectionName: https-www
      kind: Gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - name: frontend
          port: 5173
