apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mova-erinnerungsbuch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-2tvwejg-pne
      containers:
        - image: redis:8-alpine@sha256:7d509f5640f5ed199d8781b5f5a45050133efe700aed34491f0b060665066d76
          name: redis
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mova-erinnerungsbuch
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
