apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mova-erinnerungsbuch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
      containers:
        - image: redis:8-alpine@sha256:69f2c586c8a7e9cce4ae1ee9bbaf60bc4bb5f4bb3880e4ed022b1fd758a7cab9
          name: redis
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mova-erinnerungsbuch
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
